version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "${MYSQL_EXPOSED_PORT}:3306"
    volumes:
      - be-assessment-mysql:/var/lib/mysql

  app:
    container_name: student-management-api
    build: .
    env_file: .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306  
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app

volumes:
  be-assessment-mysql:
