version: "3.8"

services:
  mysql:
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT_EXPOSE}:3306
    volumes:
      - be-assessment-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  be-assessment-mysql:
